export interface Pulsera {
  id: string;
  nombre: string;
  precio: number;
  stock: number;
  etiqueta_destacada?: string;
  es_personalizable: boolean;
  descripcion_corta: string;
  descripcion_larga: string;
  imagenes: string[];
  categoria_ids: string[];
  segmento_sexo: "Femenino" | "Masculino" | "Unisex";
  coleccion_id?: string;
  material_ids: string[];
  talla_ids: string[];
  color_ids: string[];
}

const TALLAS_ESTANDAR = ["TALLA-S", "TALLA-M", "TALLA-L", "TALLA-AJ"];
const COLOR_ESTANDAR = ["COLOR-001", "COLOR-002", "COLOR-003", "COLOR-004"];
const MATERIAL_ESTANDAR = ["MAT-001", "MAT-002"];

export const PULSERAS_DATA: Pulsera[] = [
  {
    id: "PULS-001",
    nombre: "Pulsera Identidad 'PERÚ'",
    precio: 13.0,
    stock: 21,
    es_personalizable: true,
    descripcion_corta: "Accesorio artesanal ideal para mes patrio.",
    descripcion_larga:
      "Esta pulsera artesanal 'Pulsera Identidad 'PERÚ'' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en mes patrio, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
    imagenes: ["/images/puls-001.png", "/images/puls-001-1.png"],
    categoria_ids: ["CAT-001"],
    segmento_sexo: "Unisex",
    coleccion_id: "COLEC-001",
    material_ids: MATERIAL_ESTANDAR,
    talla_ids: TALLAS_ESTANDAR,
    color_ids: COLOR_ESTANDAR,
  },
  {
    id: "PULS-002",
    nombre: "Pulsera Perú Escarapela",
    precio: 14.0,
    stock: 22,
    es_personalizable: true,
    descripcion_corta: "Accesorio artesanal ideal para mes patrio.",
    descripcion_larga:
      "Esta pulsera artesanal 'Pulsera Perú Escarapela' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en mes patrio, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
    imagenes: [
      "/images/puls-002.png",
      "/images/puls-002-1.png",
      "/images/puls-002-2.png",
    ],
    categoria_ids: ["CAT-001"],
    segmento_sexo: "Unisex",
    coleccion_id: "COLEC-001",
    material_ids: MATERIAL_ESTANDAR,
    talla_ids: TALLAS_ESTANDAR,
    color_ids: COLOR_ESTANDAR,
  },
  /*
    {
      id: "PULS-003",
      nombre: "Pulsera Bandera del Perú",
      precio: 15.00,
      stock: 23,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para mes patrio.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Bandera del Perú' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en mes patrio, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-003.png"],
      categoria_ids: ["CAT-001"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-001",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-004",
      nombre: "Pulsera Perú Infinito",
      precio: 16.00,
      stock: 24,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para mes patrio.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Perú Infinito' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en mes patrio, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-004.png"],
      categoria_ids: ["CAT-001"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-001",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-005",
      nombre: "Pulsera Corazón Perú",
      precio: 17.00,
      stock: 25,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para mes patrio.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Corazón Perú' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en mes patrio, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-005.png"],
      categoria_ids: ["CAT-001"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-001",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-006",
      nombre: "Pulsera Love",
      precio: 18.00,
      stock: 26,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para san valentín.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Love' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en san valentín, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-006.png"],
      categoria_ids: ["CAT-002"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-002",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-007",
      nombre: "Pulsera Te Amo",
      precio: 19.00,
      stock: 27,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para san valentín.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Te Amo' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en san valentín, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-007.png"],
      categoria_ids: ["CAT-002"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-002",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-008",
      nombre: "Pulsera Best Friends",
      precio: 20.00,
      stock: 28,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para amistad.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Best Friends' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en amistad, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-008.jpg"],
      categoria_ids: ["CAT-003"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-003",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-009",
      nombre: "Pulsera Mamá",
      precio: 21.00,
      stock: 29,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para día de la madre.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Mamá' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en día de la madre, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-009.jpg"],
      categoria_ids: ["CAT-004"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-004",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-010",
      nombre: "Pulsera Papá",
      precio: 22.00,
      stock: 30,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para día del padre.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Papá' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en día del padre, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-010.jpg"],
      categoria_ids: ["CAT-005"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-004",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-011",
      nombre: "Pulsera Graduación",
      precio: 23.00,
      stock: 31,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para graduación.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Graduación' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en graduación, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-011.jpg"],
      categoria_ids: ["CAT-006"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-005",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-012",
      nombre: "Pulsera Feliz Navidad",
      precio: 24.00,
      stock: 32,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para navidad.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Feliz Navidad' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en navidad, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-012.jpg"],
      categoria_ids: ["CAT-007"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-006",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-013",
      nombre: "Pulsera Halloween",
      precio: 25.00,
      stock: 33,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para halloween.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Halloween' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en halloween, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-013.jpg"],
      categoria_ids: ["CAT-008"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-006",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-014",
      nombre: "Pulsera Smile",
      precio: 26.00,
      stock: 34,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para general.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Smile' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en general, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-014.jpg"],
      categoria_ids: ["CAT-009"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-007",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-015",
      nombre: "Pulsera Good Vibes",
      precio: 27.00,
      stock: 35,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para motivacional.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Good Vibes' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en motivacional, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-015.jpg"],
      categoria_ids: ["CAT-010"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-008",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-016",
      nombre: "Pulsera Hope",
      precio: 28.00,
      stock: 36,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para motivacional.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Hope' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en motivacional, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-016.jpg"],
      categoria_ids: ["CAT-010"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-008",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-017",
      nombre: "Pulsera Yin Yang",
      precio: 29.00,
      stock: 37,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para general.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Yin Yang' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en general, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-017.jpg"],
      categoria_ids: ["CAT-009"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-009",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-018",
      nombre: "Pulsera Cruz Minimalista",
      precio: 30.00,
      stock: 38,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para general.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Cruz Minimalista' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en general, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-018.jpg"],
      categoria_ids: ["CAT-009"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-010",
      material_ids: MATERIAL_ESTANDAR,
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },
    {
      id: "PULS-019",
      nombre: "Pulsera Tricolor de Tela",
      precio: 31.00,
      stock: 39,
      es_personalizable: true,
      descripcion_corta: "Accesorio artesanal ideal para mes patrio.",
      descripcion_larga: "Esta pulsera artesanal 'Pulsera Tricolor de Tela' está elaborada con materiales de excelente calidad y pensada para brindar comodidad, resistencia y un estilo único. Su diseño combina perlas acrílicas y detalles decorativos inspirados en mes patrio, por lo que es ideal para regalar o complementar cualquier atuendo. Gracias a su fabricación artesanal, cada pieza posee un acabado cuidadosamente elaborado y puede personalizarse con nombres, iniciales o pequeños cambios de color. Es un accesorio ligero, cómodo para el uso diario y perfecto para coleccionar o compartir en fechas especiales.",
      imagenes: ["puls-019.jpg"],
      categoria_ids: ["CAT-001"],
      segmento_sexo: "Unisex",
      coleccion_id: "COLEC-001",
      material_ids: ["MAT-003", "MAT-004"],
      talla_ids: TALLAS_ESTANDAR,
      color_ids: COLOR_ESTANDAR,
    },*/
];
